### ISSUE TITLE
Use node.js for this project

### ISSUE THREAD

**Issue by mmtftr** [berkalpyakici/mun_mms#1]
Hey Berk Alp,
I'd really recommend you to use node.js and js libraries. It'd be a great choice for this project and an opportunity for you to learn something new. I've looked into both of your sophisticated projects(I saw your name while using one). They're well written.
I hope you have a good day and I wish the best for your project/assignment.

**Comment by berkalpyakici** [comment]
Hello MMDF,
I'm using Node.JS library for various projects that I've not yet published. It's a great and lightweight tool for serverside scripting.

This project was written in PHP because of the limited time I had. This is also my IB CS internal assessment. Therefore, sticking with a single scripting language is easier to write a document upon.

I'll upload the whole script once my internal assessment is finished, so you might want to watch this git.

Thanks a lot for your comment 👍 , and hope to see you at MUNDP 2017 next week!

**Comment by mmtftr** [comment]
Hey, I'm looking forward to seeing you there too!
I noticed that you make big and single commits containing multiple changes. I suggest you try to do partial commits containing few changes so when you have a bug, error or need to follow back the steps of the development it'll be easier for you.
